### ISSUE TITLE
Erratic Lightroom Output on Windows with Labels and Regions

### ISSUE THREAD

**Issue by feathered-arch** [colin0brass/FaceLabellingExportLrPlugin#10]
https://www.dropbox.com/s/ylz9e3vjbbz3acs/2021-04-01_feathered_arch_testoutput_2.zip?dl=1

Here is the last test I ran with logs and settings. (content warning: bad people in those photos)

The prior run, which I did not preserve, resulted in no face regions being drawn. 

I will kill the Dropbox link when you've received it. Password is "arch" (to hide contents from search engines)

(nice work so far! thank you!!)
[2021-04-01_feathered_arch_testoutput_2.zip](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6245865/2021-04-01_feathered_arch_testoutput_2.zip)

**Comment by colin0brass** [comment]
Thanks @feathered-arch , I have downloaded your test data, so please feel free to take it down now.

Please can you help explain a bit more about the erratic behaviours you have seen?

Initial hypothesis:
I wonder if there might have been an earlier FLE export continuing in the background, interfering with the later run?
I have been trying to figure out how to terminate an export (e.g. if it is taking way too long, or maybe even stuck in an infinite loop), but so far haven't cracked it. I added a call to "FLEMain.stop" from inside "FLEExportDialogs.endDialog" for exactly this reason, but that doesn't seem to have done the trick.


Summary observations from log file:
Starts ok; exif looks consistent with labelling; finishes ok
Unexpected call to "FLEMain.stop" before "FLEMain.start"
Unexpected additional call to "property_table_init_from_prefs" in the middle of the log; Looks like it is going back through FLEInitPlugin for some reason.


Further notes:
I took a quick look through the logs and images, and so far have observed the following:

FaceLabellingExport.log:

Line 134: unexpectedly called FLEMain.stop (before FLEMain.start which isn't until line 440)
* I have recently added a precautionary call to FLEMain.stop from inside FLEExportDialogs.endDialog, since I have seen export task continuing after trying to quit it (mid-run) via the LrC main window. So I wonder if this is for some reason firing early during the export, and perhaps sometimes confusing things. I could easily remove that, but will wait to understand from you a bit more.

Line 460: Exif summary for "Joe Biggs001.jpg": contains 1 face region, though with no name given
Line 634: ImageMagick script looks to be created and executed without any reported errors, and consistent with 1 unnamed face
(File: "Joe Biggs001.jpg": consistent with the log; 1 unnamed face)

Line 651: Exif summary for "Joe Biggs002.jpg": contains 1 face region, though with no name given
Line 825: ImageMagick script looks to be created and executed without any reported errors, and consistent with 1 unnamed face
(File: "Joe Biggs002jpg": consistent with the log; 1 unnamed face)

Line 842: Exif summary for "Roger Stone003.jpg": contains 1 face region, named as "Roger Stone"
Line 1040: ImageMagick script looks to be created and executed without any reported errors, and consistent with 1 face labeled as "Roger Stone"
(File: "Joe Roger Stone003.jpg": consistent with the log; 1 face, named as "Roger Stone")

Line 1057: Exif summary for "Joe Biggs004.jpg": contains 1 face region, though with no name given
Line 1227: ImageMagick script looks to be created and executed without any reported errors, and consistent with 1 unnamed face
(File: "Joe Biggs004.jpg": consistent with the log; 1 unnamed face)

Line 1244: Exif summary for "Roger Stone, Enrique Tarrio005.jpg": contains 2 face regions, one is "Roger Stone", the other is unnamed
Line 1487: ImageMagick script looks to be created and executed without any reported errors, and consistent with 2 faces, one named as "Roger Stone"
(File: "Roger Stone, Enrique Tarrio005.jpg": consistent with the log; 2 faces, 1 named as "Roger Stone", the other unnamed)

Line 1504: Exif summary for "Roger Stone006.jpg": contains 1 face region, named as "Roger Stone"
Line 1698: ImageMagick script looks to be created and executed without any reported errors, and consistent with 1 face labeled as "Roger Stone"
(File: "Roger Stone006.jpg": consistent with the log; 1 face, named as "Roger Stone")

Line 1699: Unexpected new "property_table_init_from_prefs"; this shouldn't be happening in the middle of a log
Looks like it is going back through FLEInitPlugin for some reason.

Line 1726: Exif summary for "Ariel Kohane, Ted Cruz007.jpg": contains 2 face regions, though with no names given
Line 1941: ImageMagick script looks to be created and executed without any reported errors, and consistent with 2 unnamed faces
(File: "Ariel Kohane, TedCruz007.jpg": consistent with the log; 2 unnamed faces)

Line 1958: Exif summary for "Roger Stone, Colin Kilich008.jpg": contains 2 face regions, one is "Roger Stone", the other is unnamed
Line 2201: ImageMagick script looks to be created and executed without any reported errors, and consistent with 2 faces, one named as "Roger Stone", the other is unnamed
(File: "Roger Stone, Colin Kilich0081.jpg": consistent with the log; 2 faces, one named as "Roger Stone")

Line 2218: Exif summary for "Roger Stone009.jpg": contains 1 face region, named as "Roger Stone"
Line 2412: ImageMagick script looks to be created and executed without any reported errors, and consistent with 1 face, labeled as "Roger Stone"
(File: "Roger Stone009.jpg": consistent with the log; 1 face, named as "Roger Stone")

Line 2429: Exif summary for "Roger Stone, Enrique Tarrio010.jpg": contains 2 face regions, one is "Roger Stone", the other is unnamed
Line 2672: ImageMagick script looks to be created and executed without any reported errors, and consistent with 2 faces, one labeled as "Roger Stone", the other being unnamed
(File: "Roger Stone, Enrique Tarrio010.jpg": consistent with the log; 2 faces, one named as "Roger Stone", the other is unnamed)

Line 2673: FLEMain.stop is called here as expected, and it exits, leaving logs intact for inspection

**Comment by feathered-arch** [comment]
I think your theory about a prior process running is correct. I went to go prepare a folder for another run (which I can get to later) and noticed images in the export folder from a run I'd done earlier that apparently completed long after the run I sent to you. 

And there are still two exiftool.exe processes running in the background (not doing anything, though). 

I'll do another run later after a reboot.

**Comment by feathered-arch** [comment]
https://www.dropbox.com/s/37w7gj09sc504qc/2021-04-02%20Lightroom%20Exports.zip?dl=1

Once again this is probably more data than you need :)

Nine different runs, many are the same really. Logs included. However, the logs prior to restarting Lightroom again aren't there for your plugin as I did not realize they didn't persist between sessions.

There were no stray exiftool.exe processes between restarts so it's unlikely there were any prior unfinished background runs from a prior export. The 1st run set in the zip file was completed after a reboot ruling that theory out entirely.

The region names are in the XMP. For some reason it's just not picking up the names in those cases.
For example, with the Duncomb image:

```
xmp	
CreatorTool	Adobe Photoshop Lightroom Classic 10.2 (Windows)	
ModifyDate	2021-04-02T13:43:03-04:00	
MetadataDate	2021-04-02T13:43:03-04:00	


Iptc4xmpExt	
PersonInImage[1]	Drew Duncomb	

MP	
RegionInfo.Regions[1].Rectangle	0.681018518518518, 0.206481481481481, 0.149074074074074, 0.183333333333333	
RegionInfo.Regions[1].PersonDisplayName	Drew Duncomb	

mwg-rs	
Regions.AppliedToDimensions.w	1080	
Regions.AppliedToDimensions.h	1080	
Regions.AppliedToDimensions.unit	pixel	
Regions.RegionList[1].Rotation	0.00000	
Regions.RegionList[1].Type	Face	
Regions.RegionList[1].Area.h	0.18333	
Regions.RegionList[1].Area.w	0.14907	
Regions.RegionList[1].Area.x	0.75556	
Regions.RegionList[1].Area.y	0.29815	
```

**Comment by colin0brass** [comment]
Many thanks for this. I have downloaded the data, so feel free to take it down whenever you like.
I will try to take a closer look tomorrow.

So far I interpret there are probably at least 2 issues here:
Firstly something fragile with stray export (plugin) processes that can run-on and interfere with later exports (or at least confuse the logs).
Secondly some image meta-data not recognised or not handled properly, resulting in missing face labels.

I will look closer at the image files and meta-data soon.

Regards
Colin

**Comment by colin0brass** [comment]
On the meta-data, I took a look at one of your previous test-set images which contained two face regions but only one came through with a name label.

I interpret that the explanation is something you mentioned in-passing in issue #8  ... the meta-data in XMP:MP and XMP:mwg-rs are different. Specifically here, some of the people names are included in MP but omitted in mwg-rs.

I currently use a custom exiftool 'config file' (basically a user-specified perl script to do extra processing on the meta-data tags. In there I do try to handle multiple XMP data schemas including MP, MWG-RS and IPTC; however I didn't expect to have to parse multiple such data schemas from one image file and take the superset. I can imagine that could get very complicated, for example how to know if regions in different schema formats are actually the same, or whether they are different.

I didn't design a specific preference order for which metadata schema to pick in the case more than one is used in the same image file. I suspect which one wins could either be down to processing order of the exiftool 'config' file, or position within the XMP metadata itself. At a guess, I'd suggest that here the mwg-rs data is being picked in the end due to being later (further down) in the XMP meta-data structure. Unfortunately mwg-rs is the one where some of the person names are missing, hence the incomplete labelling.

Do you know how the metadata was generated? Would it be possible to ensure either only one region metadata schema present in the file, or that all region metadata schemas are consistent about the face labelling?

File: Roger Stone, Enrique Tarrio005.jpg

If I grep for the region data:

Region Info MP                  : {Regions=[{PersonDisplayName=Roger Stone,Rectangle=0.623611111111111|, 0.219135802469136|, 0.0657407407407407|, 0.107407407407407},{PersonDisplayName=Enrique Tarrio,Rectangle=0.247685185185185|, 0.209876543209877|, 0.0861111111111111|, 0.140740740740741}]}

Interpretation of the MP meta-data: 2 face regions; both named with "PersonDisplayName"

Region Info                     : {AppliedToDimensions={H=810,Unit=pixel,W=1080},RegionList=[{Area={H=0.10741,W=0.06574,X=0.65648,Y=0.27284},Name=Roger Stone,Rotation=0.00000,Type=Face},{Area={H=0.14074,W=0.08611,X=0.29074,Y=0.28025},Rotation=0.00000,Type=Face}]}

Interpretation of mwg-rs meta-data: 2 face regions, but only 1 is named with "Name"; the other has no "Name" tag

**Comment by feathered-arch** [comment]
[2021-04-03 Issue 10 response.zip](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6253209/2021-04-03.Issue.10.response.zip)

I'm not a programmer, but I imagine what I just noticed is the kind of thing that makes you want to tear your hair out. 

Things are fine before they get into Lightroom. Once photos get into LRC it appears LRC switches naming order between xmp:MP and xmp:mwg. It is also dropping the Region.List[x].Name at random. 

In the Newt Gingrich, A Kohane (etc) file from yesterday one interesting thing is that the export is of a virtual copy that has been cropped. The last face, Vish, is in the original image but is outside of the bounds of the applied crop. This is the only image where this is so.

I did another run, from a warm boot, this time making sure to remove the "Apply Crop" checkmark, but it made no difference.

I would downgrade back to 10.2 but that would present issues with my other current catalogs.

The catalog I'm working from was recently created for the express purpose of testing your plugin and is using images I exported FROM Lightroom once already. I imagine if I export-->import enough times all the face names will be missing :)

**Comment by feathered-arch** [comment]
So I have no idea what's going on. I re-exported images out of my other program to use to test an idea. But your plugin is working fine on them now. 

I can't see any appreciable difference in the metadata between these files other than that, for some reason, the files output on April 2nd are **Little Endian encoded.** (?!?!?!)

This contains one photo, 3 versions with the meta in a .txt file, and the meta from the exported file on April 2nd.

1. The original file used to output from Lightroom today (April 3rd); I used the Save Metadata feature on this file before export. 
2. The original file from the software I'm using (out from TTI). 
3. The output from Lightroom today (April 3rd)
4. The metadata for the file from April 2nd.

[2021-04-03 Issue 10 - addendum.zip](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6253439/2021-04-03.Issue.10.-.addendum.zip)

**Comment by colin0brass** [comment]
Thanks again for your help and supporting information @feathered-arch . I have downloaded the zip files, so feel free to take them down whenever you like.

I have started to look at the 'response' zip data, but not yet the 'addendum' data.

So far, I interpret:

Lightroom appeared to export (in both included exports) as little-endian, from source files that were big-endian. From a very quick search online I think this might be configurable during the export somewhere, but I didn't spot it when quickly firing-up LrC and looking in the export settings. I might look again later, but I suspect this should be academic, and not contribute to the actual issues.

Lightroom export appears to be truncating the mwg-rs region "Name" list, despite preserving the rest of the region information. I wonder if they might be favouring the MP metadata format, and perhaps this might possibly be an unnoticed bug in the mwg-rs handling in Lightroom? I should probably look rather deeper on my side first though to be more sure what is going on before casting aspersions on Lightroom.

In my plugin I do deliberately process from the image file exported from Lightroom, not from the source file read into Lightroom. I felt that was the safest approach from an image file damage risk perspective, and I thought that might also help support more image file formats by utilising inbuilt capabilities of Lightroom that I am unlikely to be able to achieve independently.

So I can think of a couple of options here:
1. I could change my plugin to process from the source image (not the exported image); either always, or as a config option; that might help bypass this apparent truncation of mwg-rs name data
2. I could add an option of which XMP data to use (or perhaps less error-prone, which ones to *ignore*). So for example, to use the MP metadata and ignore mwg-rs

First however I'll take a closer look later at the other data you provided, and try some tests to see if I can figure out more about what is going on.

For the other aspect with apparently stray processes and unexpected interleaved entries in the log file, I am wondering about going to separate FLE log files per export run, with time-stamps in file names. That would be a bit less convenient for development purposes, having to track down and individually open the latest log file, however it would probably help to pin-down if the export completed cleanly, and avoid mixing-up of log entries.

Thanks again.

Regards
Colin

**Comment by colin0brass** [comment]
I have done some searching for any known LrC issues that might be contributing to this behaviour.

This one seems close, though I haven't managed to interpret if it does overlap or not:
- https://feedback.photoshop.com/conversations/lightroom-classic/lightroom-person-keyword-only-fills-people-shown-iptc-extended-tag-on-export/5f5f45784b561a3d424e6c5b

Finding this one too, gives me the feeling that LrC is not treating mwg-rs as a first-class citizen for output:
- https://feedback.photoshop.com/conversations/lightroom-desktop-cloudbased/lightroom-cc-for-desktop-photos-lose-mwg-regions-when-saved/5f5f45f04b561a3d426943da

I suspect this one is not directly relevant, but it adds to my overall feeling that LrC has a number of deficiencies around region handling:
- https://feedback.photoshop.com/conversations/lightroom-classic/lightroom-facial-recognition-data-not-saved-potential-data-loss/5f5f45774b561a3d424e4255

**Comment by colin0brass** [comment]
My current thoughts (not yet implemented) on way forward are:
1. Add a mechanism in FLE plugin and through into exiftool config file to give a "preferred" XMP schema (e.g. MP vs MWG vs IPTC) to use in the case that more than one is present in the image file; thinking to set (or at least default) that as "MP" based on observations about LrC behaviour to-date
2. Change FLE plugin logging to use unique time-stamped log files per export run; a bit less convenient for development, but could hopefully help pin-down any issues with stray tasks etc, as well as see if multiple concurrent exports are/can be supported

**Comment by colin0brass** [comment]
I've added a priority order  for selecting XMP format, starting with MP (if present in file) and pushed it to GitHub master (not yet as tag or release). It seems ok on the test files I have tried so far, but I'm not sure I have the most problematic images in my test library yet. Please could you help give it a whirl too and let me know how it behaves for you?

**Comment by feathered-arch** [comment]
As to your question from two days ago, it seems MWG is an actual standard but MP is proprietary. I think your answer is purely a question of which is more popular, and who you're targeting as an audience for this plugin. 

I'll give it a whirl when I can.

**Comment by feathered-arch** [comment]
[20210411.zip](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6292334/20210411.zip)

Looks good!

**Comment by colin0brass** [comment]
That's great news. Thanks for confirming.
I will issue an updated release with this soon, though I am thinking about changing the logging to unique time-stamped file per export at the same time, to help pin-down any remaining issues with stray tasks or multiple exports.
