### ISSUE TITLE
Exporting with geolocation metadata

### ISSUE THREAD

**Issue by kolreed** [colin0brass/FaceLabellingExportLrPlugin#12]
Hi Colin, thanks for the great plugin, just what I need - almost! 

The exports work great and I have no problem with the labels so far. My photos are geotagged and have the location metadata fields filled in. I've unchecked the 'Remove exif' option when exporting. Most of the metadata comes across to the new image, but the location metadata doesn't.

I found the generated ImageMagick command script, so I ran the export on a single image, then re-exported using the stock Lightroom hard drive exporter with the 'Remove location info' option in the Metadata options unchecked. Then I ran imagemagick manually using the generated script and the location data was successfully copied across.

I suspect that when you export the initial image from Lightroom that the option to 'Remove location info' is on by default.
Is it possible to change that behaviour or make the Metadata options available when using your plugin?

Thanks, Colin

**Comment by colin0brass** [comment]
Thanks for reporting this - my own use-case for this plugin has been for family history photos, and none of them had included location data.

I have done an update which I think will do what you want, but I don't have any suitable images in my test set yet.

Please could you possibly help test the update and let me know if it works?
The update should be there both on master and also as tag v1.10.

I chose to keep metadata export settings section hidden since it could cause problems if a user disabled metadata export from LR, which would then break the plugin. So in the name of robustness and ease of use, I disabled the metadata export settings section. So for this update I have applied a specific override to enable location metadata to be included in the export from LR to the plugin.

Just in case ... the settings are at the end of file: FLEExportServiceProvider.lua
New setting applied in function: updateExportSettings
`    exportSettings.LR_removeLocationMetadata = false -- include location data in export
`
And the code block immediately following that defines the 'export service table', including to hide the metadata section:
`    hideSections = { 
        'metadata', 'outputSharpening', 'video', 'watermarking' },
`

Regards
Colin

**Comment by kolreed** [comment]
Thanks Colin, I can confirm that this now works - the location data is exported to the image. 

It also removes the location data if the 'Remove exif' option is selected on export. 

Thanks!

Colin

**Comment by colin0brass** [comment]
That's good news. Thank you for helping to test and confirm.

Regards
Colin
