### ISSUE TITLE
Gratitude, and feature request

### ISSUE THREAD

**Issue by torroslo** [colin0brass/FaceLabellingExportLrPlugin#13]
I just downloaded your latest and was pleased to see the additional export controls since I first used this plugin a year ago.  I wanted to thank you again for this work.  

I found that the automated label placement worked quite well on non-dense images of people, but would occasionally trip on itself (obscuring other labels or faces) if the density of people got too high.  I solved most of those problems by selecting a fixed font size and finding the largest that would avoid obscured labels.  

I will again plea for being able to select the label font, though I understand the value of using the monospaced courier font.  Is there a sans serif monospaced font choice available?  It would also be nice to have some more detailed explanations for the various export options.  Thanks again for maintaining this useful plugin!

**Comment by colin0brass** [comment]
Thanks for the feedback @torroslo. I will take a look into doing selectable fonts - my general worry is keeping it compatible between different computers, but I do recognise and appreciate the request.

**Comment by colin0brass** [comment]
Hi @torroslo, some updates:

### Font Type
I have added font type selection (using ImageMagick to list available system fonts), and tested it successfully on both Mac and Windows. See tag & release v1.11 published to GitHub just now.

Please could you give it a try and let me know if it works for you?

The font list on Windows can be quite long, and the drop-down menu navigation is a bit primitive, but I don't know of a better way, and it does seem to work.

In an ideal world the drop-down list would also show what every font looks like, but that felt like it would add a lot of complexity for something that the user can do outside of the plug-in, so I chose to keep it simple.

It uses ImageMagick to list available system fonts. In case of problems, or to check what fonts ImageMagick knows about, try something like the following on the command-line (adding path to ImageMagick app if you need to): `magick -list font` or on a linux-like system with "grep" available, to get a more condensed font list: `magick -list font | grep Font`

### Labelling Challenges
On the labelling problems with high density of people, yes I recognise that the plug-in can struggle in those situations.

You might find it helpful to set different "label initial values" - e.g. label position "above" instead of "below", or a smaller initial font size.

The plug-in iterates many different labelling experiments to try to avoid clashes of labels with faces and other labels, but they can take a long time (especially when exporting multiple photos at a time; and needing to re-render each label text each time they change layout, to get the new dimensions) and I found it necessary to set a limit to the number of experiments it is allowed to try for each photo. Those limits are currently: Low=50, Medium=100, High=200, Very High=500. The default is currently "High", so you might consider trying "Very High" in case it finds a more successful labelling outcome, though I suspect many cases will still not improve.

I have limited the number of options to make each labelling experiment, since the overall number of combinations can already be huge. Label position: above/below/left/right; Label number of rows: 1/2/3/4; Font size multiples: 1/0.75/0.5/0.25.
So as mentioned above, initial label font size might be one of the most obvious candidates to help in dense situations.

If you are interested in what it is trying, you can set the logging level to "Debug" or "X-Debug", and view the resulting Plug-in log file to see all the experiments it tried and what clashes it detected.

I have considered whether there could be a smarter way to find the best labelling positions (for example, something based on a model of magnetic repulsion), but nothing I have tried so far has given any better result or user experience. Associated with that, I did wonder about giving it flexibility to move the label further away from the person, but this quickly also adds complexity, both in the algorithm, and also to ensure the labelling is still clear about who is who. So I don't have any current plans for a major re-work.

**Comment by torroslo** [comment]
Hi colinObrass,

Thanks for the prompt font choice feature!  It is way more than I expected (I thought only a small curated set would be possible).  Don’t worry about showing the font name in its style, there are other ways to know what they look like.

I made a quick check that it works on my 2021 MacBookPro (Monterey 12.2) and I am happy with the result.  I am currently not able to give this as much testing as I’d like until later this week.  As you note there are real challenges to automatic labelling, so it is nice to have some manual controls.  I can provide more feedback and suggestions if you are interested, though this might not be the best channel for that exchange.

Regards,
Thor
