### ISSUE TITLE
misaligned labels and boxes

### ISSUE THREAD

**Issue by matharvest** [colin0brass/FaceLabellingExportLrPlugin#2]
Hey Colin,

I'm using Lightroom clasic 10.1 on Windows and tried to do a test export, but the lables and boxes were misaligned 

not sure what other details you might need 

I've taken a screen grab of how Lightroom is positioning the face rectangles  and how it looks after the export 

let me know if you need any more details / information, etc. thanks 

![test_original_screencap](https://user-images.githubusercontent.com/76715780/103254274-61564100-49d0-11eb-988a-dcd76baa7a20.JPG)

![text_export](https://user-images.githubusercontent.com/76715780/103254277-661af500-49d0-11eb-8af0-3ad248aabd92.jpg)

**Comment by colosb01** [comment]
Hmm, that looks curious. Thanks for flagging the issue.
I just updated to LrC 10.1 and re-ran on my test images and they are still fine.

From your screenshots, the scale and spacing looks about right, but with an overall horizontal and vertical shift.

I'm quite new to the details of handling EXIF region data, but I suspect there might be variations in the way the regions are represented in that data, and that I don't yet have a sufficiently broad compatibility). I will take a closer look, see if I can deduce the solution from basic principles, or alternatively might look to add some debug instrumentation and ask if you can help run something to try and help diagnose.

Regards
Colin

**Comment by matharvest** [comment]
Hey Colin, Happy to help out any way I can .... I've done a fair bit of scripting / coding in my time, but nothing with illustrator ... but let me know if you want me to test anything

**Comment by colin0brass** [comment]
Sorry for the delay (it took me a while to put down other things ongoing), but I have now been able to look into this further.

Initially I thought it might have been differences in region encoding in EXIF, but having looked deeper, and batch-downloaded a few thousand images from Google Images to experiment on, I now strongly suspect it is simply that I wasn't handling cropped images properly.

When I was first developing this plug-in I quite deliberately kept it simple, and didn't want to include code that I didn't have test-cases for. I think this is exactly such a case, but now I clearly need to address it.

I have been thinking about how best to handle this, and it is leading me to restructure the program a bit, which I think will make it easier to understand and maintain. I am in the middle of that now, but it is taking me on a bit more of a voyage of discovery through what can be done in exiftool, and how best to interact with that from the plugin.
ExifTool is amazingly capable, but is taking me a while to get my head around: https://exiftool.org

In the meantime, if you wanted to check if there is indeed crop meta-data in your image, you should be able to use console/terminal command something like the following:

Command on Mac:
`exiftool <image_file> -j -'*crop*'`
I think on Windows the type of quotes need to be changed as follows:
`exiftool <image_file> -j -"*crop*"`

If you want to see the region data too, then if it is in MWG format (from the 'Metadata Working Group') then you should be able to use:
`exiftool <image_file> -j -'*crop*' -XMP-mwg-rs:all`
or again for Windows I think that would be:
`exiftool <image_file> -j -"*crop*" -XMP-mwg-rs:all`

If the region data is in Microsoft format then this should help:
`exiftool <image_file> -j -'*crop*' -XMP-MP:all`
or again for Windows I think that would be:
`exiftool <image_file> -j -"*crop*" -XMP-MP:all`

Notes:
- If exiftool isn't in your search path then include full executable path & filename
- Insert your image file path & name in place of <image_file>

**Comment by colin0brass** [comment]
I think this should be fixed in tag v1.2 today, but I don't have access to a Windows machine just now to test on, so it is only currently tested on Mac.

I have added a config file (get_regions.config) for exiftool, which is basically a perl script, to extract the region information (supporting multiple metadata formats), converts to absolute pixels, handles crop & rotation, and outputs the resulting regions ready for the plug-in to use. As well as supporting more metadata types, crop & rotation, this also has the advantage of simplifying the region coordinate handling in the plug-in. Hopefully this means that any updates to the region handling should now be confined to the config file.

I have added some options in the PlugIn Manager to help locate the application files and log file. I have also added capability to change the logging verbosity.

In the Export dialog, I have made the file naming & sizing options visible, since I didn't seem to be able to get the behaviour that I wanted as default.
I have also added an option to output cropped thumbnail images. I previously had a separate plugin for this, but it was quite straightforward to combine and can also be a useful way to quickly visually inspect the face region detection across lots of images.

@matharvest , please could you help test this update and tell me if it a) works at all on Windows; and b) resolves the misaligned labels and boxes issue?

Hmm, I've just run another test image and realised one limitation / potential-improvement ... I interpret that the LightRoom inbuilt image export process is giving the full original image, rotated but without the crop being applied. That doesn't loose anything, and works fine with the face labelling, but isn't necessarily what you want to see having carefully cropped the image. I propose to add an option to apply the crop on the exported image ... but it would be good to hear from you first if possible to know if there is anything else that needs doing too.

Regards
Colin

**Comment by matharvest** [comment]
Hey Colin,

Awesome, that looks to have fixed that problem that I was seeing, the alignment is now good - one little thing that tripped me up initially was that you have to make sure that in the export window under Metadata that your exporting All Metadata and  "remove person info" is not ticked - I assume the process runs exiftool.exe over the exported file to determine where the face tags are located and gets around the cropping issue.

Its not a problem to export that data, but not sure if its something that you can check as part of the scripts?

thanks 

Mat.

**Comment by colin0brass** [comment]
Ah, thanks for that Mat. I happen to have always used "Image Format = Original" in the File Settings section of the Export dialog box ... and this automatically enables the metadata export (in fact, greys-out the metadata export settings so they can't be changed). But trying it now, I see that just about any other "Image Format" does leave metadata export configuration options, and by the sounds of things, it is either an LrC default, or a common user preference, to leave metadata export disabled, hence tripping up anyone trying to use this plug-in for face labelling.

I have found the corresponding settings in the exportSettings data structure, so now need to add it either as a self-check/warning, or an over-ride.

Thanks for letting me know.

Regards
Colin

**Comment by colin0brass** [comment]
Ok, adding the face meta-data export setting override seems to have been straightforward enough (famous last words). I then disabled the metadata section in the export settings dialog to avoid confusion.

I have pushed v1.3 with that update, so hopefully that should remove one stumbling-point in using this plug-in.

Could you possibly give it a go Mat and let me know if it works for you too?

**Comment by colin0brass** [comment]
From comments above (and further communication & testing), I interpret this issue is resolved now, so I propose to close this ticket within the next week or two unless I hear otherwise. Let's say in case I forget, that if I look back on this after end of March 2021, then if no further comments then I will close this issue without asking further.

**Comment by matharvest** [comment]
one minor comment - didn't look like you incremented the version number. Not sure if that was related, but I had to completely remove the old plug-in (as in disable / remove from LightRoom then delete the folder, etc) before it worked. 

But yes, the issue appears to be resolved - Thanks
