### ISSUE TITLE
Export settings

### ISSUE THREAD

**Issue by feathered-arch** [colin0brass/FaceLabellingExportLrPlugin#8]
This belongs in a "discussion" section most likely, but...

I'm trying to make sense of the export settings particularly with dynamic label locations and dynamic label sizes. 

"Central Astronaut in Blue" is a label I can't get to shrink. I can't get any of them to shrink any further than what you see here, and I'm probably doing something wrong. The runover of the 'central astronaut' caption is mighr be due to the fact that the people next to her do not have any face regions? But in the half-cropped image that label displays as it should.

See file 

for originals and exported: [2021_03_14.zip](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6137613/2021_03_14.zip)
log: [log.txt](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6137633/log.txt)

![calibration_guy up top, SECOND FRONT, NASA ASTRONAUT 1, FRONT ROW ASTRONAUT, Center Astronaut in Blue, NEEDS MORE SUNLIGHT, Up Top Astronaut, NASA ASTRONAUT 2, Johan Von Dingleberry, ASTRONAUT 5, WHY ONLY ONE-](https://user-images.githubusercontent.com/37090381/111084835-cd821480-84ea-11eb-89c3-4c2c84e67ba6.jpg)

Cheers!
-Me

**Comment by feathered-arch** [comment]
Yep, I'm confused. This was done using the default settings except that I turned on the face and label boxes.


[dingleberries log.txt](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6137785/dingleberries.log.txt)
![dingleberry test on 1000 x 1000 pixel grid](https://user-images.githubusercontent.com/37090381/111087079-f6f46d80-84f5-11eb-9634-35650b207c97.jpg)

**Comment by colin0brass** [comment]
Thanks for asking. I have been intending to add some more explanation about the label sizing and position search algorithm, and should add that to the README soon. I do also suspect there is significant room for improvement in how this process works and therefore in the resulting layout of the labels.

The general mechanism at present goes something like this:

1. Choose overall font size (either as fixed value, or as exponential search, based on export config options)
- note, the 'dynamic' font size will aim for certain label width relative to average face size, but also taking account of the relative size of the face regions to the overall image; the idea here is that a small face region benefits from a label up to several times wider than the face itself, but we wouldn't want to do that if the face region is already a large proportion of the image
- this is the first place that I can imagine your scenarios above might start to diverge in terms of layout selection

2. Try the default label config; label position (above, below, left, right); number of text rows per label (1,2,3,4,5); and font size
- if there are clashes, then do a recursive search to find successful layout; trying different positions and number of rows, for all of the clashing labels

3. If that doesn't sort it, then try reversing the clash list and start from the other end; in case that helps flush out a viable solution that was missed the first  time around

4. If that didn't do it either, then try reducing the font size to 75% and try again
5. Another font size reduction
6. One final font size reduction
7. Use default


That is about how it works today. I suspect this might be both inefficient and also due to 'depth-wise recursion' be too inclined to dive straight down to niche solutions rather than try all the 'obvious' ones first. I have some thoughts in mind about an improved algorithm.

**Comment by colin0brass** [comment]
Hi @feathered-arch , it took me a while to straighten-out my thinking on this, but I have implemented a proposed multi-label recursive position & format algorithm. I have pushed it to master, but not yet created as tag or release in case it doesn't behave itself in the wider world.

Please could you help give it (from master) a test and see if it seems like an improvement to you?

Behind the long sentence above, basically the differences are:
- 1) I fixed a mistake in the initial (dynamic) font size optimisation, so this should get to a better initial font size (when dynamic size is enabled)
- 2a) Previously it would only try to optimise the label format (position, num rows, font size) for one clashing label at a time
- 2b) Now tries all combinations of all clashing labels vs format (position, num rows, font size)

Notes:
- It treats label position (above/below/left/right) and num rows (1,2,3,4,5) as individual per-label options.
- Where-as font size is treated as a global parameter, so if it needs to shrink the size for 1 label then all are made consistent.

Known limitations:
- The label formatting experiments are not yet user configurable - I have shown their values in export dialog, but not yet added widgets for user configuration. To-do.
- On tricky label layouts, the recursive search can sometimes get horribly deep & long. The worst examples were before I found the bug in the dynamic font size algorithm, and it has been much better behaved since, so I hope that is ok now. I did add a limit on the max number of experiments it would try before calling a halt and reverting to which-ever one had lowest label overlap area, so this should help avoid too ridiculously long run-times. I am thinking to make the iteration loop limit configurable in case users want to allow it more attempts & time.
- It is somewhat of a 'brute-force' approach, trying all combinations for all clashing labels. I have a vague thought in mind that there might be smarter algorithms, and even something relatively simple might help like "if there are lots of clashes then reduce the font size straight away".

Regards
Colin

**Comment by feathered-arch** [comment]
I've attached the output using the default settings. 

Note that I do make use of a keyword, 'Nil', in my catalog, in a custom plugin field called "Parse 1" (from the John Beardsworth Search Replace Transfer), to denote people who do not have any faces as I do not use Lightroom's built-in facial recognition. 

[20210324 FLELP test1.zip](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6201133/20210324.FLELP.test1.zip)

So if it isn't your plugin adding "Nil" I am puzzled as to how it is getting this information, and why it's ignoring the proper metadata. My understanding is the information is taken from the Region Name which is correct in those files.

**Comment by colin0brass** [comment]
Ah, I had just about spotted that in passing on one image, but incorrectly assumed it was from the metadata.

Yes, that was from trying to handle a case with purely numeric name, however then the LUA tostring conversion function was trying too hard to be helpful when there was no name defined, and so converted it to 'nil'.

It is clearly useful to also have the unnamed face regions, since that helps with where to put (or not to put) the labels for those that /do/ have names.

I have added detection of undefined names from the EXIF to avoid the 'nil' strings, and to skip label creation if there is no name string.

I have pushed the fix for this (again to master, not yet as a tag or release). Please could you give this a try and see if it now does a better job?

Regards
Colin

**Comment by feathered-arch** [comment]
So this is interesting. I tried this again without updating. Photos which
Lightroom has recognized as having people with names exported just fine. If
I enable the facial recognition I am guessing it imports that data from the
IPTC into some special place, and your plugin works.

Since I don't work this way there's a complication for you. But I imagine
most people will have photos tagged within Lightroom like this. So I may
not be the typical use case for this software.

Will try updated version next.

**Comment by feathered-arch** [comment]
![Capture](https://user-images.githubusercontent.com/37090381/112501966-0f6b5000-8d60-11eb-85dc-673a0851fd7c.PNG)
Thumbnails aren't writing with a jpg extension, and there's nothing to indicate what they're referring to. (using the default 'Region Name' setting)
This problem only occurs with the 'Region Name' setting.

Face region outlines were drawn -- even the incorrect ones that Lightroom helpfully added . However, there are no longer any labels produced except for those photos that Lightroom has accepted as a 'known' face.

**Comment by feathered-arch** [comment]
UPDATE:

I reverted to 1.6 but still had the same issue. I resolved it by removing the photos from the catalog, and then re-importing them. 

This fixed the issue. I suspect a Lightroom bug of some sort may be involved. 

Attached is the output on Windoze with the default settings. 

[Win 1.7 output.zip](https://github.com/colin0brass/FaceLabellingExportLrPlugin/files/6212444/Win.1.7.output.zip)

**Comment by feathered-arch** [comment]
**The following is more information than you'd like:**

If it matters any, I'm on Lightroom 10.2.

The moment I open the People view, and despite settings not allowing this to happen, Lightroom joyfully starts its process of identifying and tagging everyone. Nonetheless I no longer have the issue mentioned in the previous post. As such this does not appear to be the (consistent) cause of any problems except for.....

.... The images process successfully, however there are now two sets of thumbnails.
![image](https://user-images.githubusercontent.com/37090381/112648057-7e5bae00-8e1f-11eb-9ea0-6add80c15032.png)

HOWEVER.... once I run another plugin, which is a utility that uses Google Cloud Vision to populate fields and detect face information...... and I am not making this up..... the problem is solved. No duplicate tags. (?!?!?)

But what is interesting is the labels changed from the default of BOTTOM to the UPPER LEFT of the region.  This behavior is not consistent and was observed only once. I mention in case it means anything to you.

HOWEVER... if I close out of Lightroom, and reopen, the labels revert to the default BOTTOM position. 

If you want, I can create a small catalog of sample photos that I use for testing your plugin -- that is free of any other plugins manipulating the data -- as these are all really confounding problems that you probably don't want to address at this stage of development. 

FYI, all of the data changing is only in Lightroom. I have not been saving the metadata back to the image files as I have a separate program I'm using for tagging faces (the Cloud Vision thing is an experiment that is not working well.) The metadata from exported files is the same as the original.

Another thing, in case it matters, is that the XMP:MP and the XMP:mwg-rs are slightly different in my photos:

```
**MP**	
RegionInfo.Regions[1].Rectangle	0.328666666666667, 0.0889679715302491, 0.326666666666667, 0.266903914590747	
RegionInfo.Regions[1].PersonDisplayName	John Doe

**mwg-rs**	
Regions.AppliedToDimensions.w	750	
Regions.AppliedToDimensions.h	1124	
Regions.AppliedToDimensions.unit	pixel	
Regions.RegionList[1].Rotation	0.00000	
Regions.RegionList[1].Name	John Doe	
Regions.RegionList[1].Type	Face	
Regions.RegionList[1].Area.h	0.26690	
Regions.RegionList[1].Area.w	0.32667	
Regions.RegionList[1].Area.x	0.49200	
Regions.RegionList[1].Area.y	0.22242	
```

**Comment by colin0brass** [comment]
Thanks again. I have now added a check of the thumbnail name when using region name as filename, and substituted 'Unknown' if it would otherwise be blank. That has improved the filename itself, resolved the missing file type suffix, and also an issue where it would not be saved into subdirectory if specified.

Update has been pushed to master (but not yet tag or release).

I am thinking to add some more user control of the new features in the export dialog before I then publish as new release.
