### ISSUE TITLE
Export from previous error

### ISSUE THREAD

**Issue by feathered-arch** [colin0brass/FaceLabellingExportLrPlugin#9]
See image
![Capture](https://user-images.githubusercontent.com/37090381/112488933-5c492980-8d54-11eb-8598-0236146d7fd8.PNG)

**Comment by feathered-arch** [comment]
Using the 'Export from previous' option causes the above error.

**Comment by colin0brass** [comment]
Thanks for this ... I hadn't even spotted this export menu option before, hence the bug.

Because it triggers an export without opening the normal dialogs, it bypassed how I was initialising the export parameters and including user preferences.

I have added an initialisation step at the start of the actual export, to ensure it is done even if the dialogs are bypassed by using the "Export with previous" menu option.

Update pushed to master for this now.
(I will look later at the other issue ticket, so you might want to wait for that one too before doing any new testing)
